wallpaper {
    monitor = DP-5
    path = ~/pictures/wallpaper.jpg
    fit_mode = contain
}

wallpaper {
    monitor = DP-4
    path = ~/pictures/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/pictures/wallpaper2.jpg
    fit_mode = cover
}
