# backup for backwords compatibility 
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

# top monitor
monitor = DP-4, 1920x1080@60, 0x0, 1
# bottom monitor (directly below DP-4)
monitor = DP-5, 1920x1080@120, 0x1080, 1
# portrait on the right of both (90° rotation)
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1, transform,3

$mainMod = SUPER
$terminal = foot #kitty #foot
$fileManager = nautilus
$menu = wofi --show run #rofi -show run

# exec-once = waybar & hyprshot & swaync & hypridle

bind = $mainMod, T, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, hyprlock 
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, space, exec, $menu

# move/resize windows with Super + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# move focus with Super + hjkl
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

# move windows with Super + Shift + hjkl
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, l, movewindow, r

# resize with Super + Ctrl + hjkl
bind = $mainMod CTRL, h, resizeactive, -50 0
bind = $mainMod CTRL, l, resizeactive, 50 0
bind = $mainMod CTRL, k, resizeactive, 0 -50
bind = $mainMod CTRL, j, resizeactive, 0 50

# Go to workspace 1–10
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move focused window to workspace 1–10 (stay where you are)
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Next / previous workspace
bind = $mainMod, i, workspace, r+1
bind = $mainMod, o,  workspace, r-1

# Screenshots
#bind = , s, exec, hyprshot -m window
#bind = shift, s, exec, hyprshot -m region

input {
  kb_layout = de 
}
