#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
# This ensures that if any command fails, the script will stop.
set -e

# --- Configuration ---
# Define the directory where custom SSH configurations will be stored.
# This makes it easier to manage and include in your main ~/.ssh/config.
SSH_CONFIG_DIR="$HOME/.ssh/conf.d"
# Define the specific file where compute instance SSH configurations will be added.
CPD_CONFIG_FILE="$SSH_CONFIG_DIR/cpd.conf"

# --- Part 1: Select Cluster ---
echo "Fetching available clusters from xa1rkeclusters.cdc.a1.group..."

# 'k get ... -o name' typically outputs 'resource.group/name'.
# 'awk -F'/' '{print $2}'` extracts just the 'name' part.
# 'fzf' provides an interactive fuzzy finder for selection.
# The selected cluster name is stored in the CLUSTER variable.
CLUSTER=$(kubectl get xa1rkeclusters.cdc.a1.group -o name | awk -F '/' '{print $2}' | fzf --prompt="Select a cluster: ")

# Check if a cluster was selected. If not, exit the script.
if [ -z "$CLUSTER" ]; then
    echo "No cluster selected. Exiting."
    exit 1
fi

echo "Selected cluster: $CLUSTER"

# --- Part 2: Retrieve SSH Key for the Selected Cluster ---
# Define the path where the SSH key will be saved.
SSH_KEY_PATH="$HOME/.ssh/$CLUSTER"

echo "Attempting to retrieve SSH private key 'sshkey-$CLUSTER'..."

# Fetch the base64-encoded private key from the Kubernetes secret.
# Decode it using base64 -d and redirect the output to the specified file.
# If the 'k get' command fails, print an error and exit.
if ! kubectl -n crossplane-system get secrets "sshkey-$CLUSTER" -o jsonpath="{.data.private}" | base64 -d > "$SSH_KEY_PATH"; then
    echo "Error: Could not retrieve SSH key 'sshkey-$CLUSTER'."
    echo "Please ensure the secret exists in your Kubernetes cluster and you have permissions to access it."
    # Remove any partially written or empty file if an error occurred during retrieval.
    rm -f "$SSH_KEY_PATH"
    exit 1
fi

# Set crucial permissions for the private key file.
# SSH requires private keys to have permissions of 600 (owner read/write only).
chmod 600 "$SSH_KEY_PATH"
echo "SSH private key for '$CLUSTER' saved to $SSH_KEY_PATH with permissions 600."

# --- Part 3: Generate SSH Config Entries for Compute Instances ---
echo "Generating SSH config entries for compute instances related to cluster '$CLUSTER'..."

# Add a clear header to the cpd.conf file for better organization.
# This makes it easy to see which entries were generated by this script and when.
echo "" >> "$CPD_CONFIG_FILE" # Add a newline for separation from previous content
echo "# --- START: Auto-generated entries for cluster '$CLUSTER' on $(date) ---" >> "$CPD_CONFIG_FILE"

# Fetch all compute instances, filter them, and generate SSH config entries.
kubectl get computeinstances.exoscalea1.crossplane.io | \
    grep -E "$CLUSTER" | \
    awk '{print $1, $5}' | \
    # Loop through each extracted instance name and IP address.
    # 'read -r INSTANCE_NAME INSTANCE_IP' reads space-separated values into two variables.
    while read -r INSTANCE_NAME INSTANCE_IP; do
        # Ensure both instance name and IP are not empty before proceeding.
        if [[ -n "$INSTANCE_NAME" && -n "$INSTANCE_IP" ]]; then
            echo "Host $INSTANCE_NAME" >> "$CPD_CONFIG_FILE"
            # Using the instance's IP address as the Hostname.
            echo "    Hostname $INSTANCE_IP" >> "$CPD_CONFIG_FILE"
            # Default SSH user for the compute instance. Change 'ubuntu' if your instances
            # use a different default user (e.g., 'ec2-user', 'centos', 'root', etc.).
            echo "    User root" >> "$CPD_CONFIG_FILE"
            # Specify the private key file that was retrieved earlier.
            echo "    IdentityFile $SSH_KEY_PATH" >> "$CPD_CONFIG_FILE"
            echo "  -> Added config for instance: $INSTANCE_NAME (IP: $INSTANCE_IP)"
        fi
    done

# Add a footer to the cpd.conf file.
echo "# --- END: Auto-generated entries for cluster '$CLUSTER' ---" >> "$CPD_CONFIG_FILE"
echo "" # Add a blank line for readability

echo "SSH config entries have been added/appended to $CPD_CONFIG_FILE."
echo ""
echo "--- Important: Final Step ---"
echo "To make these configurations active, you need to include the generated file"
echo "in your main ~/.ssh/config file. If you haven't already, add the following line:"
echo ""
echo "  Include $CPD_CONFIG_FILE"
echo ""
echo "inside your ~/.ssh/config file (e.g., near the top)."

echo "Script finished successfully."
